name: build tinygo

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        os: ['ubuntu-latest', 'macos-latest']
      fail-fast: false

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download llvm-build
        working-directory: compiler
        run: |
          wget https://github.com/uuosio/build-llvm/releases/download/v0.0.1/llvm-build-${{ matrix.os }}.tar.gz
          tar -xf llvm-build-${{ matrix.os }}.tar.gz
      - name: Build tinygo
        working-directory: compiler
        run: |
          make llvm-source
          make wasi-libc-eosio
          make
          make release
      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: compiler
        run: |
          ./build/tinygo help
      - name: get release file
        id: releasefile
        working-directory: compiler
        run: |
          echo "::set-output name=value::$(python scripts/get_release_file.py)"
      - name: release-tinygo
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./compiler/build/${{ steps.releasefile.outputs.value }}
