name: build tinygo

on:
  push:
    branches: [ dev ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    env:
      GSCDK_VERSION: v0.1.6
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        # os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']
        python-version: [3.9]
        os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']
      fail-fast: false

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install wget
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install wget --no-progress
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache llvm-build v11
        uses: actions/cache@v2
        id: cache-llvm-build-v1
        with:
          key: ${{ matrix.os }}-llvm-build-v11-v1
          path: tinygo/llvm-build
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build llvm
        if: steps.cache-llvm-build-v1.outputs.cache-hit != 'true'
        working-directory: tinygo
        run: |
          cp -r ../eosio.cdt/eosio_llvm llvm-project
          make llvm-build
          ls llvm-build/lib/LLVMEosioApply.*
