name: build tinygo

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        os: ['windows-latest']
      fail-fast: false

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install wget
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install wget --no-progress
      - name: Download llvm-build
        working-directory: compiler
        run: |
          wget https://github.com/uuosio/build-llvm/releases/download/v0.0.1/llvm-build-${{ matrix.os }}.tar.gz
          tar -xf llvm-build-${{ matrix.os }}.tar.gz
      - name: Cache wasi-libc sysroot
        uses: actions/cache@v2
        id: cache-wasi-libc
        with:
          key: ${{ matrix.os }}-wasi-libc-sysroot-v1
          path: lib/wasi-libc/sysroot
      - name: Build wasi-libc
        if: steps.cache-wasi-libc.outputs.cache-hit != 'true'
        working-directory: compiler
        run: make wasi-libc
      - name: Cache wasi-libc-eosio sysroot
        uses: actions/cache@v2
        id: cache-wasi-libc-eosio
        with:
          key: ${{ matrix.os }}-wasi-libc-eosio-sysroot-v1
          path: compiler/lib/wasi-libc-eosio/sysroot
      - name: Build wasi-libc-eosio
        if: steps.cache-wasi-libc-eosio.outputs.cache-hit != 'true'
        working-directory: compiler
        run: make wasi-libc-eosio
      - name: Build tinygo
        working-directory: compiler
        run: |
          make llvm-source
          make
          make release
      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: compiler
        run: |
          ./build/tinygo help
      - name: get release file
        id: releasefile
        working-directory: compiler
        run: |
          echo "::set-output name=value::$(python ../scripts/get_release_file.py)"
      - name: rename file
        working-directory: compiler
        run: |
          mv ./build/${{ steps.releasefile.outputs.value }} ./build/uuosio.gscdk-v0.1.3-${{ matrix.os }}.tar.gz
      - name: release-tinygo
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./compiler/build/uuosio.gscdk-v0.1.3-${{ matrix.os }}.tar.gz
